### Project specific config ###

language: c

matrix:
  include:
    - os: linux
      env: ATOM_CHANNEL=stable
      lua: lua5.1
      lua: luajit2.1

    - os: linux
      env: ATOM_CHANNEL=beta
      lua: lua5.1
      lua: luajit2.1

env:
  global:
    APM_TEST_PACKAGES: "language-lua"

before_script:
  - luac -version
  - luajit -v

### Generic setup follows ###
script:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - "./build-package.sh"

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

git:
  depth: 10

sudo: false

dist: trusty

addons:
  apt:
    packages:
    - build-essential
    - fakeroot
    - git
    - libsecret-1-dev
